server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gyhhlw_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice

mybatis:
  type-aliases-package: edu/ecopm/pojo
  configuration:
    map-underscore-to-camel-case: true
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #logging:
  #  level:
  #    eud.zhu.user: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
pattern:
  name: 本地环境local

